Failing to update to rc5
fails with "java.lang.NoClassDefFoundError: Could not initialize class org.apache.maven.api.xml.XmlService" a class which is not used in any of the mojos or their tests.

(cherry picked from commit f801ee5981b7314d1974782053034d169b3e714b)